### Get all contacts
GET https://cse341-project1-rfos.onrender.com/contacts

### Get one contact
GET https://cse341-project1-rfos.onrender.com/contacts/690a7491f7d639793e7305ce

### Create a new contact
POST https://cse341-project1-rfos.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Luis",
  "lastName": "De la Rosa",
  "email": "luis@example.com",
  "favoriteColor": "Blue",
  "birthday": "1998-04-15"
}

### Update
PUT https://cse341-project1-rfos.onrender.com/contacts/ID_A_ACTUALIZAR
Content-Type: application/json

{
  "firstName": "Luis Updated",
  "lastName": "De la Rosa",
  "email": "luisupdated@example.com",
  "favoriteColor": "Green",
  "birthday": "1998-04-15"
}

### Delete
DELETE https://cse341-project1-rfos.onrender.com/contacts/ID_A_BORRAR
